name: Remove Problem Statements
on:
  push:
    branches:
      - main
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Remove problem READMEs but keep root README
        run: |
          find . -type f -name "README.md" ! -path "./README.md" -delete
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Remove problem statements" || echo "No changes to commit"
          git push
