name: Sanitize README

on:
  push:
    branches:
      - main

permissions:
  contents: write  # ✅ Allow pushing changes back to the repo

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # ✅ Use built-in token

      - name: Sanitize README files
        run: |
          for dir in */ ; do
            if [ -d "$dir" ]; then
              folder_name=$(basename "$dir")
              slug=$(echo "$folder_name" | cut -d'-' -f2-)
              title=$(echo "$slug" | sed -r 's/-/ /g' | sed -r 's/\b(.)/\u\1/g')
              echo "# $title" > "$dir/README.md"
              echo "[View on LeetCode](https://leetcode.com/problems/$slug/)" >> "$dir/README.md"
              echo "" >> "$dir/README.md"
            fi
          done

      - name: Commit sanitized files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Sanitized README to remove problem statements" || echo "No changes"
          git push
